# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class MudrexOnyx < Formula
  desc "Onyx is a small wrapper over AWS SDK to perform some console ui tasks easily via command line!"
  homepage ""
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/mudrex/onyx/releases/v0.0.8/onyx_0.0.8_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "02e0cd19697a11b716efad4bde632d0fe3e60c51652734f178cfc7853cab610e"

      def install
        bin.install "onyx"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/mudrex/onyx/releases/v0.0.8/onyx_0.0.8_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "22c612e32351da0640bf435893ba2d4ba314ed14bd098adc1f4726200de3aa8d"

      def install
        bin.install "onyx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/mudrex/onyx/releases/v0.0.8/onyx_0.0.8_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cba7f60c1121353e337961f7c2cfb52a85efe3fd01bbc469c3a04c000ff16612"

      def install
        bin.install "onyx"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/mudrex/onyx/releases/v0.0.8/onyx_0.0.8_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1806e32d5cbe98cdb143abb6ee20bff0cfaabeda7e0ac6f15f608918e19f9410"

      def install
        bin.install "onyx"
      end
    end
  end
end
