# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MudrexOnyx < Formula
  desc "Onyx is a small wrapper over AWS SDK to perform some console ui tasks easily via command line!"
  homepage ""
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/mudrex/onyx/releases/v0.0.9/onyx_0.0.9_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8414d6e3ee18081f580e6b5ea3526884d2c453f94247db5636d80ea5de16dd1a"

      def install
        bin.install "onyx"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/mudrex/onyx/releases/v0.0.9/onyx_0.0.9_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "db0872d6fafc82236185534c2270f8f4f8897c40ba288c3adc9db371e3efb646"

      def install
        bin.install "onyx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/mudrex/onyx/releases/v0.0.9/onyx_0.0.9_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e3566a84d53e4ed620399d0b84cee646e60e8012917f30cc38d0809e28ddf556"

      def install
        bin.install "onyx"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/mudrex/onyx/releases/v0.0.9/onyx_0.0.9_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7184129626d37f9d816aea4a3b7c6384c1234e3b5bf648464b12309cb502e66f"

      def install
        bin.install "onyx"
      end
    end
  end
end
