# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onyx < Formula
  desc "Onyx is a small wrapper over AWS SDK to perform some console ui tasks easily via command line!"
  homepage "https://github.com/mudrex/homebrew-onyx"
  version "0.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/mudrex/onyx/releases/download/v0.0.16/onyx_0.0.16_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5cc898118c44c1ca6ecb9d31f3329de63db4aaaa80f8aa26dc8083abe39d4ce7"

      def install
        bin.install "onyx"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/mudrex/onyx/releases/download/v0.0.16/onyx_0.0.16_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0e36062964d1851f1f57c456ec02e8cf16229bfd8acbe23aa727ada190ac356a"

      def install
        bin.install "onyx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/mudrex/onyx/releases/download/v0.0.16/onyx_0.0.16_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e7bb3b5a0987e7d1a9cf4d1f90253f8b33bc9b34e7e923ad6bba33c653625ab9"

      def install
        bin.install "onyx"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/mudrex/onyx/releases/download/v0.0.16/onyx_0.0.16_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f55ded2b1b8701014e9c02d469ba35a8f87d2adb219234b7144e465ab19851f5"

      def install
        bin.install "onyx"
      end
    end
  end
end
